networks:
  caching-network:
    driver: bridge
    
volumes:
  preference_data:

services:
  directoryofpreferences:
    image: ${DOCKER_REGISTRY-}directoryofpreferences
    build:
      context: .
      dockerfile: DirectoryOfPreferences/Dockerfile     
    container_name: preferences-service
    restart: always
    depends_on:
      - redis
      - preference_db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5000
      ConnectionStrings:Redis: redis:6379,ssl=False,abortConnect=False
      ConnectionStrings:Postgres: "Host=preference_db;Port=5432;Database=Preference;UserId=postgres;Password=admin6"
    ports:
      - 5000:5000
    networks:
      - caching-network

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - caching-network
  
  preference_db:
    image: postgres
    container_name: preference_db
    restart: always
    environment:    
      POSTGRES_DB: Preference
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin6
    volumes:
      - 'preference_data:/var/lib/postgresql/data'
    ports:
      - '5436:5432'
    networks:
      - caching-network